version: '3'

services:
  postgres:
    image: postgres:10
    volumes:
      - exam-postgres:/var/lib/postgresql/data
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: champ
      POSTGRES_PASSWORD: champ
      POSTGRES_DB: champ
  redis:
    image: redis
volumes:
  exam-postgres:
    driver: local

