version: '3'

services:
  postgres:
    image: postgres:10
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: random
      POSTGRES_PASSWORD: random
      POSTGRES_DB: champ
  exam-online-backend:
    image: studyabacus/exam-online-backend
    build: .
    ports:
      - "6969:6969"
    depends_on:
      - postgres
    environment: 
      DB_USER: random
      DB_PASS: random
      DB_NAME: champ
      DB_HOST: postgres
    env_file:
      - .env
