version: '3'

services:
  postgres:
    image: postgres:10
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: champ
      POSTGRES_PASSWORD: champ
      POSTGRES_DB: champ
  redis:
    image: redis
  exam-online-backend:
    image: studyabacus/exam-online-backend
    build: .
    volumes: 
      - ./api:/usr/src/exam-online-backend/api
    ports:
      - '6969:6969'
    depends_on:
      - postgres
      - redis
    environment:
      DB_USER: random
      DB_PASS: random
      DB_NAME: champ
      DB_HOST: postgres
      REDIS_HOST: redis
    env_file:
      - .env
